set -x
export VLLM_ATTENTION_BACKEND=XFORMERS
ENGINE=${1:-vllm}


# model_path=/mnt/cfs_algo_bj/models/opensource_model/Qwen/Qwen2.5-VL-7B-Instruct
# model_path=/mnt/cfs_algo_bj/models/experiments/shenyucheng/checkpoints/SFT/1500_slide/qwen2.5_vl_full_final-7B
model_path="/mnt/cfs_algo_bj/workspace/shenyucheng/VRAG/qwen2.5_vl_full_final-SlideVQAsft"
# resume_model_path=/mnt/cfs_algo_bj/models/experiments/shenyucheng/checkpoints/0226-final1/checkpoints/vrag/SFT_w_crop_8_gpus_10_maxturns_5_ngroups_qwen2_5_vl_7b/
n_gpus=$(nvidia-smi -L | wc -l)

train_batch_size=8
ppo_mini_batch_size=$((1 * n_gpus))
ppo_micro_batch_size_per_gpu=1
log_prob_micro_batch_size_per_gpu=1
n_agent=5

# # test
# train_batch_size=4
# ppo_mini_batch_size=4
# ppo_micro_batch_size_per_gpu=1
# log_prob_micro_batch_size_per_gpu=1
# n_agent=2

tensor_model_parallel_size=2
val_before_train=False
# rm_url="https://qianfan.baidubce.com/v2/chat/completions"
rm_url="https://www.huayanapi.com/v1/chat/completions"
# rm_model_name="deepseek-v3.2"
rm_model_name="qwen3-max-2026-01-23"
search_url="http://0.0.0.0:8004/search"
# rm_key="REDACTED_API_KEY" # set your dashscope api key here
rm_key="REDACTED_API_KEY" 
max_turns=10
project_name="vrag"
experiment_name="SFT_w_crop_${n_gpus}_gpus_${max_turns}_maxturns_${n_agent}_ngroups_qwen2_5_vl_3b"

export RAY_memory_usage_threshold=0.995
HYDRA_FULL_ERROR=1 python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=grpo \
    data.train_files=./data/slidevqa-train.parquet \
    data.val_files=./data/vidoseek_train.parquet \
    data.train_batch_size=$train_batch_size \
    data.max_prompt_length=8192 \
    data.max_response_length=2048 \
    data.image_key=images \
    actor_rollout_ref.model.path=$model_path \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.actor.optim.lr_warmup_steps=5 \
    actor_rollout_ref.actor.optim.lr_warmup_steps_ratio=0.285 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=$ppo_mini_batch_size \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=$ppo_micro_batch_size_per_gpu \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.01 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.entropy_coeff=0 \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=True \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=True \
    actor_rollout_ref.actor.state_masking=True \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=$log_prob_micro_batch_size_per_gpu \
    actor_rollout_ref.rollout.tensor_model_parallel_size=$tensor_model_parallel_size \
    actor_rollout_ref.rollout.name=$ENGINE \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.4 \
    actor_rollout_ref.rollout.enable_chunked_prefill=False \
    actor_rollout_ref.rollout.enforce_eager=False \
    actor_rollout_ref.rollout.free_cache_engine=False \
    actor_rollout_ref.rollout.n=1 \
    actor_rollout_ref.rollout.n_agent=$n_agent \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=$log_prob_micro_batch_size_per_gpu \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    reward_model.reward_manager='rm' \
    reward_model.rm_workers_num=10 \
    reward_model.rm_url=$rm_url \
    reward_model.rm_key=$rm_key \
    reward_model.rm_model_name=$rm_model_name \
    algorithm.kl_ctrl.kl_coef=0.0 \
    trainer.critic_warmup=0 \
    trainer.logger=['console','wandb'] \
    trainer.project_name=$project_name \
    trainer.experiment_name=$experiment_name \
    trainer.n_gpus_per_node=$n_gpus \
    trainer.nnodes=1 \
    trainer.save_freq=25 \
    +trainer.save_at_end=True \
    trainer.test_freq=0 \
    +trainer.total_step=100 \
    trainer.resume_mode=disable \
    trainer.val_before_train=$val_before_train \
    retriever.url=$search_url \
    max_turns=$max_turns $@